#!/bin/bash
#
# This is the control script of the n3tpd

JAVA=/usr/bin/java
JARFILE=n3tpd.jar
LOGFILE=n3tpd.log
PIDFILE=n3tpd.pid

case "$1" in
     start)
            echo "Starting n3tpd daemon..."
            java -jar n3tpd.jar &
            PID=$$
            let "PID += 1"
            echo $PID > $PIDFILE
            ;;
     stop)
            echo "Stopping n3tpd daemon..."
            PID=$(cat n3tpd.pid)
            kill $PID
            ;;
     restart)
            echo $($0 stop)
            echo $($0 start)
            ;;
     status)
            echo ""
            ;;
     *)
			echo "Missing parameter"
			echo "Usage: n3tpd [start|stop|restart|status]"
            ;;
esac

exit 0